blank_issues_enabled: true
contact_links:
  - name: Question or problem with a specific project
    url: https://github.com/GLiNet-Community-Scripts
    about: Open the issue in that project's repository in the organization.
